# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
      - "bkimminich"
    default_labels:
      - "dependencies"
    ignored_updates:
      - match:
          dependency_name: "express-jwt"
          version_requirement: "0.1.3"
      - match:
          dependency_name: "sanitize-html"
          version_requirement: "1.4.2"
      - match:
          dependency_name: "unzipper"
          version_requirement: "0.9.15"
      - match:
          dependency_name: "jsonwebtoken"
          version_requirement: "0.4.0"
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    target_branch: "develop"
    default_reviewers:
      - "bkimminich"
    default_labels:
      - "dependencies"
